### ISSUE TITLE
Make menu visible / invisible on button press

### ISSUE THREAD

**Issue by hackintoshlover** [davetcc/tcMenu#178]
Hi Dave,
I was trying to implement the visibility parameter but unfortunately not able to get it through.
Basically i have modified the analogdfrobot code to make "onLED2" visible when "onLED1" == true and make "onLED2" invisible when "onLED1" == false
It only turns visible but does not turn back to invisible when selected
Also its not instant after selecting the parameter i need to go back to main an enter again
Kindly refer to the attached video for reference
https://drive.google.com/file/d/1d5FChufHFT5iFiripVTWxWNIBY4cnSMh/view?usp=drivesdk
Final Question: How do i make a menu visible on long press of a switch and turn it back to invisible on selecting "exi
![Screenshot (86)](https://user-images.githubusercontent.com/40655406/141892308-4dbae177-6514-4cf0-a04f-b9e5eb4fd7b9.png)
t"

**Comment by hackintoshlover** [comment]
Library versions all latest
Arduino version 1.8.13

**Comment by davetcc** [comment]
Can you please ask questions in the forum? https://www.thecoderscorner.com/jforum/recentTopics/list.page

It keeps the noise down in here.

After changing the visibility of menu items, you need to tell the menu manager the structure has changed, see https://github.com/davetcc/tcMenuLib/blob/f690c27345e735c040e4b62c0590f3b82ab568fa/src/tcMenu.h#L340

Unless there is a bug, please close and if need be open a question on the forum. Even there, there's no guarantee of an answer, but I try and answer things on a best efforts basis if it doesn't take too much time.

**Comment by davetcc** [comment]
There was an issue with the menuMgr structure change notification handler. This will be released in V2.2.5 of tcMenuLib due shortly: 

https://github.com/davetcc/tcMenuLib/issues/130

This release depends on 2.1.0 of IoAbstraction and will be due soon.
