### ISSUE TITLE
Allow users to customize timeout value after which the menu is reset to root

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenu#222]
When using TcMenu library, I noticed that once I go into a sub-menu and don't touch the display for 30 seconds, the menu hierarchy is reset back to root (top menu).

I have implemented some menu screens with status information which is periodically refreshed. While looking at the display we hardly press any buttons. For usecases like mine, it would be great if TcMenu allowed us to configure custom timeout value or turn this feature completely off.

![IMG_20220924_150417](https://user-images.githubusercontent.com/4460766/192099598-3b422b07-08ac-4c8d-9ed1-667ff1b741bd.jpg)

**Comment by davetcc** [comment]
Take a look at http://thecoderscorner.com/products/arduino-libraries/tc-menu/renderer-take-over-display/#functional-approach-to-capturing-display-timeout--reset as that may do what you want.

**Comment by vzahradnik** [comment]
Thanks, I will have a look.

**Comment by davetcc** [comment]
The rendering of the boolean items seems a bit misaligned there, I'll take a look at many boolean items on the same page and see if any tidying up is needed.

**Comment by vzahradnik** [comment]
Might be but this is not much of an issue for me. I still work on a prototype so this is good enough. I have some bigger features in mind. Once I have something concrete, I will create separate issues and we can discuss there.

Your advice helped. I dig through the `MenuManager` code as I thought the logic was there. I should check the renderer, too :)

Thanks for your help!
