### ISSUE TITLE
Can't select the whole text with "CMD+A"

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#226]
When my cursor is in an input box, I usually use "cmd+a" hotkey to select the whole text.
But "cmd+a" is also the hotkey for "save as".
So when I want to select the whole text with hotkey, I would always call out the "save as dialog".
Once the "save as dialog" was called out, the current project will be changed to untitled.emf,  and I can't save my progress to my project.

I wish these improvements can be made:
1. Unbind the "save as" hotkey, because It's not frequently used. Or change to "cmd+shift+s" as VSCode does.
2. When "save as dialog" is cancelled, don't change current project.

Thanks for all the great work, really like your library!

**Comment by davetcc** [comment]
Agreed, I'm a mac user myself but I'd never really noticed this, I'll move the hotkey to something else.
