### ISSUE TITLE
bug: renderer.turnOffResetLogic() not working

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#234]
tcMenu version
---
2.5.0 （2.4.x can also reproduce）

How to reproduce:
---
1. open example simpleU8g2
2. add `renderer.turnOffResetLogic();` before `setupMenu()`
3. build, upload, enter menu `settings`
4. wait 30s
5. menu will return to root 

But it should never leave the submenu automatically because of `renderer.turnOffResetLogic();`

**Comment by davetcc** [comment]
It probably needs to be made clearer in the documentation but any methods on menu manager or renderer should only be called after setupMenu, as the object is uninitiated before that. But I’ll see if it is possible to handle this during initialisation.

**Comment by luwenjin** [comment]
I see, I'll try to reorder the code on Monday. 😄

**Comment by luwenjin** [comment]
`renderer.turnOffResetLogic();` after `setupMenu()` works!
If the order is important and impossible to change, maybe add a warning or raise an exception ?

**Comment by luwenjin** [comment]
`renderer.turnOffResetLogic();` after `setupMenu()` works!
If the order is important and impossible to change, maybe add a warning or raise an exception ?

**Comment by davetcc** [comment]
Exceptions are turned off on most boards, even for operator new so I don't think that would work. Maybe we could add a logger warning, indicating "Menu System is not yet initialized" but how many people use IoLogging, not really that sure. I will make sure it's properly documented though

**Comment by davetcc** [comment]
I will add an IoLogging warning if any set method is called before init. I think it's the best we can do.

**Comment by davetcc** [comment]
See https://github.com/davetcc/tcMenuLib/issues/165
