### ISSUE TITLE
bug: no underline at first, when edit very large numeric item 

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#235]
tcMenu version:
---
2.5.0

Problem:
----
When editing "very large numeric item", there should be an underline for the number that is editing.
But at the time entered edit mode, there was no line under the first number at first.
However after changing it's value, the underline appeared.

**Comment by davetcc** [comment]
Found this one, it was an ordering bug, where the editor range was checked before the value had been requested, it is requesting the value that sets the cursor positioning.
