### ISSUE TITLE
UI bug: ctrl+v in input will paste twice

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#236]
When Editing menu item, if I use ctrl+v to paste any text into input, the text will be paste twice.

**Comment by davetcc** [comment]
Good spot, thanks for raising these issues. This one is a tricky one and seems to be something that has changed in JavaFX platform integration on at least macOS and maybe others. I can't recreate it on Windows, but it happens nearly every time on macOS.

It actually seems that although the copy-and-paste functions have accelerators attached to menu items, these are not overriding the copy-and-paste behaviour fully, resulting in the paste operation taking place twice on affected machines. I'll need to do a bit more digging on this one to see what's causing it, as both 2.4.0 and 2.5.0 were built with the same JDK, maybe I'll try and older JDK for now.
