### ISSUE TITLE
UI: Unclear meaning for "Default Value" checkbox in BooleanMenuItem

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#237]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/251550/198499932-cdc2c723-922a-4560-b1f0-868c5dcdd865.png">

Does it Means "Default ON/YES/TRUE"?

**Comment by davetcc** [comment]
Agreed, on reflection it would be better as a combo box with the names. I’ll change it.

**Comment by davetcc** [comment]
![image](https://user-images.githubusercontent.com/12195465/198823830-9d6fbc38-ef82-4ba9-a4a8-c29a7d922b4c.png)

I think this makes more sense.

**Comment by luwenjin** [comment]
> ![image](https://user-images.githubusercontent.com/12195465/198823830-9d6fbc38-ef82-4ba9-a4a8-c29a7d922b4c.png)
> 
> I think this makes more sense.

Very Clear! 👍
