### ISSUE TITLE
Add method to save single MenuItem's value to EEPROM ?

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#250]
I have a bunch of settings  under `Settings` Menu, and I also have some standalone options under other menus.

These stand alone options need to be saved when changed.
But currently, it seems I can only save the whole menu data to EEPROM at once, which may feel a bit odd to the users.

It would be nice if we can save single MenuItem's value to EEPROM.

**Comment by davetcc** [comment]
Yep looked at the code and it is really trivial with very little risk (and well unit tested too), I'll add that in 3.0, tracking https://github.com/davetcc/tcMenuLib/issues/167
