### ISSUE TITLE
BUG: after renderer.giveBackDisplay() + menuMgr.activateMenuItem(&secondItem), first moving down attempt is now working

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#254]
There might be 2 bugs: 

1. I selected my second menuItem under a submenu, after `renderer.takeOverDisplay();` and `renderer.giveBackDisplay()` in the callback, I found the cursor is on the first child item (which should be on the 2nd item like before taking over display).
2. Due to bug 1, I ran `menuMgr.activateMenuItem(&secondItem)` after `renderer.giveBackDisplay()`, the cursor position is correct. But when I press DOWN for the first time, the cursor won't move down, after pressing for the 2nd time, the cursor moved and working smoothly afterwards. (if I press UP at first, no problem at all).

**Comment by davetcc** [comment]
At the moment, giving back the display does a reset of the current menu. In many menu designs, this occurs when there's a reset timeout and the user UI takes over control. 

Point 2 should be fixed in 3.0.0 because of another issue that was reported in the forum.

**Comment by davetcc** [comment]
This should be fixed in 3.0.
