### ISSUE TITLE
bug: after menuMgr.activateMenuItem, "down" twice needed to move the cursor down

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#282]
version: 3.0.1

After calling `menuMgr.activateMenuItem`
If I want to move the cursor down, I need to hit down button twice, afterwards the navigation is all fine.
Moving the cursor up has no issue.

**Comment by davetcc** [comment]
See https://github.com/davetcc/tcMenuLib/issues/192

**Comment by davetcc** [comment]
See tcMenuLib issue above, already fixed and will be in 3.2
