### ISSUE TITLE
Designer Bug: move menu up/down will focus on root

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenu#300]
How to reproduce: 
1. select a menu item (other than the root)
2. click move up / move down button
3. the focus will be on root, the selected menu item is no longer focused

**Comment by davetcc** [comment]
I'm going to remove the up-down buttons from the designer and get cut/copy/paste, and drag and drop working properly See 
#303 and  #302

**Comment by luwenjin** [comment]
Great!

**Comment by davetcc** [comment]
I'm closing this and focusing on the other two issues. Will be fixed by #303
