### ISSUE TITLE
Designer: Drag & Drop Support

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenu#303]
It would be great to have drag and drop support to move items inside menu tree with our mouse. This could potentially replace the arrows to move the items, see the screenshot.
![image](https://user-images.githubusercontent.com/4460766/219452135-e89685c8-fd2e-405a-a5eb-bf17511beed1.png)

**Comment by davetcc** [comment]
This turns out to be well supported by JavaFX, will fix #302 at the same time.
