### ISSUE TITLE
Menudesigner 3.1 OS X gui bug

### ISSUE THREAD

**Issue by tomelgato** [davetcc/tcMenu#306]
On some input fields (in my case Menu Variable Name) with long text the cursor disappears at the end under the x, you dont see the last 2-3 characters while editing
![image](https://user-images.githubusercontent.com/92522434/219981958-da01310c-f46f-4cfd-80e9-1dca87845979.png)

**Comment by luwenjin** [comment]
Me too, might be blocked by the X icon

**Comment by davetcc** [comment]
Yep, it seems to be an issue with the theme we are using, I'll need to see if I can adjust the theme to remove this annoyance (or make the boxes bigger so it rarely happens. One of the two.

**Comment by tomelgato** [comment]
Bigger boxes would be no good solution. How big should they be? I have rather long names due to nested menus so it would not work in this case or you need to do annoying long boxes which are not needed in most of the cases.

**Comment by davetcc** [comment]
These are coming from the theme we are using, I suspect I'm doing something that is throwing off the theme, but it is going to need me to create a standalone app with the theme and see what happens there, and then if need be raise a bug in the source theme library. Moving out of 3.2 for now.

**Comment by tomelgato** [comment]
Bug still exists in 4.0

**Comment by davetcc** [comment]
I thought the answer to this was going to be really complex, but it turns out there is a really easy way, in the global style I just tuned off the right button, it seems to work. Based on https://github.com/JFXtras/jfxtras-styles/issues/180

It will be in 4.1

**Comment by davetcc** [comment]
![image](https://github.com/davetcc/tcMenu/assets/12195465/756f1c2e-7da8-4c51-abda-09a55d70b744)

See above no cross icon on right.
