### ISSUE TITLE
Adafruit_SPITFT error with ST77xx screen

### ISSUE THREAD

**Issue by THAWINKELS** [davetcc/tcMenu#312]
When generating an code for an TFT ST7735 screen my Arduino IDE gives the error @file tcMenuAdaFruitGfx.h

tcMenuAdaFruitGfx.h:108:26: error: variable or field 'drawCookieCutBitmap' declared void
 void drawCookieCutBitmap(Adafruit_SPITFT* gfx, int16_t x, int16_t y, const uint8_t *bitmap, int16_t w,
                          ^~~~~~~~~~~~~~~

Does anyone know where this error is from?

**Comment by davetcc** [comment]
Have you checked all libraries and the UI are up to date? Please check all versions. What is the environment that you are using?

**Comment by THAWINKELS** [comment]
Hi,

All the libary's are updated to the last (see picture)
![image](https://user-images.githubusercontent.com/85311838/222096619-cfa70ce1-38b7-4c8a-8b3a-9f03f0a5a963.png)

I'm working om Windows 8 x64, Arduino IDE with Arduino UNO.

Adafruit_GFX libary is on version 1.11.5

![image](https://user-images.githubusercontent.com/85311838/222097446-fe37efa6-611b-487d-b378-97ad17470a54.png)

**Comment by davetcc** [comment]
Graphical displays other than OLED using the SSD1306Ascii are not supported on Uno, there is not enough memory.

Even if you got past the compile error, it would not link due to a lack of available memory. The smallest 8-bit board that works for graphical displays is MEGA2560.

**Comment by davetcc** [comment]
OK, can you please zip up a test project and attach it so I can look at what's got generated?

**Comment by davetcc** [comment]
BTW - Uno works well with LCD displays that are wired directly (EG DfRobot shield for example) and also for OLED using SSD1306Ascii. We even have products running live on Uno with a direct LCD connection!

**Comment by davetcc** [comment]
Ah yes, the old IDE does not update, you often need to close and reopen the project if a file changes outside. The new 2.0 IDE and platformIO do not have this limitation.

**Comment by THAWINKELS** [comment]
Hey,

I'm currently testing with an arduino mega2560 but the error is back, I only changed the pins in the code generator.
See attachment.

[DisplayMenuTest.zip](https://github.com/davetcc/tcMenu/files/10875048/DisplayMenuTest.zip)

**Comment by THAWINKELS** [comment]
![image](https://user-images.githubusercontent.com/85311838/222530519-f77f1f72-a15c-420f-911f-a697eb17b47e.png)
Adafruit_ST7735 gfx(10, 9, 8);   (libary is up to date)
Gives the error

When I change the display type:
![image](https://user-images.githubusercontent.com/85311838/222530622-029c36ea-3811-406e-afd1-bac0cfc7c9e7.png)

Adafruit_ILI9341 gfx(10, 9, 8);
There is no error.

So something with the ST7735 libary is wrong.
**I deleted all ST7735 libarys and install them again, error is gone.**

**Comment by THAWINKELS** [comment]
![IMG20230302224725](https://user-images.githubusercontent.com/85311838/222564826-afc20cde-53a2-48aa-9675-79c8a1d792e8.jpg)

When I load the sample program (change some pin settings) I don't see the right menu text,
Do I miss something?

Inside the menu, the text is better:
![image](https://user-images.githubusercontent.com/85311838/222565680-1380c088-8810-41b0-b815-a458f3a12363.png)

**Comment by davetcc** [comment]
What platform is selected in designer, that looks like a progmem issue. It must be set to AVR for Mega and Uno.

**Comment by THAWINKELS** [comment]
Thanks!

**Comment by davetcc** [comment]
Can we close this now?

**Comment by davetcc** [comment]
Assuming this was fixed by moving to using the right platform? If not please reopen.
