### ISSUE TITLE
Designer: tcMenu Code Designer UI mismatches / improvements

### ISSUE THREAD

**Issue by NachtRaveVL** [davetcc/tcMenu#320]
After going through an entire abstraction layer with tcMenu in it, I came across a series of improvements/changes I believe you could make to the tcMenu GUI code generator in order to make it a bit more clear.

1) When it talks about "frame buffering height" values (near the end of the Adafruit style display setup), the code actually describes this value as "sprite height." It may not be apparent to newcomers (such as myself) that the two are one in the same. It might be worth indicating this in the UI, perhaps something like "Frame buffer height (aka max sprite height)" or similar.

2) RS pins -> on many different TFT breakout boards this is DC instead of RS. I have taken to calling this pin RS/DC as a result just because the two are so interchangeable. I've seen similar for the backlight pin, described on some boards as LED and BL on others. I think it's probably just safer to always refer to some of these pins using the common names associated with the majority of on-market devices.

3) SW vs HW SPI setup -> For various setups, the pins being asked for (particularly MOSI, MISO, etc), are only for SW but the label next to the input box doesn't indicate it on some setup screens as it does others. While some screens have the (SW) note in the text label, there are numerous setup screens that do not. It would be really pertinent to include that, because - story time - it caused me to scramble thinking I had to provide the library those pins before realizing, no, that's only if you're doing it under software mode. Again, little hints like that can make all the difference.

Also, thank you Dave for all your hard - just wanted to give you a shout out for all the hard work you have put into this so that devs such as myself can have a decent UI overtop of something they poured their heart and soul into.

**Comment by davetcc** [comment]
As a result of providing resource bundles (i18n for the UI) I rationalized all the strings, I think they all use the same text now, so they should be more consistent. However, should you see one that's not clear there's a single resource bundle with all the text in, so raising a PR to fix is much easier - https://github.com/davetcc/tcMenu/tree/master/xmlPlugins/core-display/i18n

**Comment by davetcc** [comment]
I'll actually leave this open, feel free to take a look through the EN resource bundle and make improvements if you think anything is still unclear.

**Comment by davetcc** [comment]
I think 3.2 should fix most of these, if after 3.2 comes out you think some issues still exist, please do reopen.
