### ISSUE TITLE
4.0 release for PlatformIO

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenu#360]
**Is your feature request related to a problem? Please describe.**
Please publish the latest release into PlatformIO registry, including all related libraries. Thanks!

![image](https://github.com/davetcc/tcMenu/assets/4460766/6c01d2e0-b3d8-4096-bfdc-ef90c621d074)

**Comment by davetcc** [comment]
Ah yes, an oversight. Will do it as soon as I can.

**Comment by davetcc** [comment]
should be good, please close if they are properly published

**Comment by vzahradnik** [comment]
Thanks! Closing now.
