### ISSUE TITLE
[i18n] Display field values instead of cryptic %menu.[number].name

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenu#374]
**Is your feature request related to a problem? Please describe.**
After the internationalization is enabled, the fields in the EEPROM layout window are not readable. Instead, users see the reference to the text field, like %menu.35.name.

**Describe the solution you'd like**
Technically it's not a bug but it would be great to load at least strings from the default language. Seeing layout like this makes the layout view not as usable.
![image](https://github.com/davetcc/tcMenu/assets/4460766/8c76875d-938e-4a31-bda7-916703a7b979)

**Comment by davetcc** [comment]
Agreed, will add to 4.1

**Comment by davetcc** [comment]
Also found a few more places, fixed them up at the same time:

* On the analog item page, the example values shown in labels were also wrong, showing units that were not localized.
* On the search menu item page, there were also similar issues, fixed there too.

**Comment by davetcc** [comment]
Same for the "Menu Item -> Show Preview" option, now correctly uses the currently selected locale as selected when opened.
