### ISSUE TITLE
TCMENU 4.0 UI bug

### ISSUE THREAD

**Issue by tomelgato** [davetcc/tcMenu#389]
There seems to be a little bug when you try to move a menu entry before or after a SubMenuItem. You can drag it on the SubMenuItem to move it inside but there is no way to put it before the Submenu. This becomes obvious when you have 2 SubMenuItems and you like to move something in between
(TCMenu 4 running on OS X)

![image](https://github.com/davetcc/tcMenu/assets/92522434/32df09a5-4741-40ac-99d4-9ad8df63d22f)

**Comment by vzahradnik** [comment]
I too have encountered issues like this. As far as I know this is not a new bug in TcMenu 4.1.1. Also moving items from submenu to the top hierarchy is buggy. Sometimes I edit the project file in text editor to achieve the hierarchy I want.

**Comment by davetcc** [comment]
Can we please come up with a list of the cases that don't work properly and I will try and fix them in 4.2?

**Comment by davetcc** [comment]
I'm going to have to do a patch release next day or two anyway as there is a critical bug that would affect new users around the create project workflow. It was not caught by the unit tests so managed to get into the release! I think I have a fix that makes this behaviour much better for at least the simple the cases.

**Comment by tomelgato** [comment]
I can confirm, 4.1.2 fixes that issue! Thanks!
