### ISSUE TITLE
Plugin folder should be stored directly within the installed app

### ISSUE THREAD

**Issue by tomelgato** [davetcc/tcMenu#400]
See also https://github.com/davetcc/tcMenu/discussions/399

When you upgrade from 4.0 to 4.1 TCmenu writes the (4.1.1) plugin dependencies into ~/.tcmenu which are used for tcmenu 4.0 as well

The problem is here that 4.0 and 4.1 are not fully backward compatible, so you cannot use tcmenu 4.0 besides 4.1 to edit an old 4.0 project

**Comment by davetcc** [comment]
Actually, this led me to a solution that I should have used years ago, just let the installer put the plugins in place instead of the app itself. The default plugins should never be used by any other version anyway.

**Comment by davetcc** [comment]
Will be part of 4.2.
