### ISSUE TITLE
FileWatcher doesn't work

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenu#420]
**Describe the bug**
When I add new strings into language property files and have the designer open, it won't reflect the changes in generated files. I have to exit the designer and re-open.

**To Reproduce**
- Open TcMenu designer and enable i18n
- In some text editor add a new string into the property file
- Generate the code

**Expected behavior**
Generated code contains the extra strings.

**Comment by davetcc** [comment]
@vzahradnik no rush but please test as you have time and then close.

**Comment by vzahradnik** [comment]
Tested and verified. Filewatcher implementation looks good!
