### ISSUE TITLE
API Docs: doxygen sorting struct members alphabetically

### ISSUE THREAD

**Issue by ptapping** [davetcc/tcMenu#76]
There are a few places in the API documentation where it states that a struct "must have these fields in this order", however it looks like doxygen is being helpful and sorting the entries alphabetically, which then makes the information incorrect.

Example:
https://www.thecoderscorner.com/ref-docs/tcmenu/html/_menu_items_8h.html#struct_any_menu_info

**Comment by davetcc** [comment]
Many thanks for reporting, I'll take a look at the doxygen command I'm running to generate the documentation.

**Comment by davetcc** [comment]
Option located and fixed up in my web-server script. next time it pulls tcmenu after a release it will correctly act upon the members.
