### ISSUE TITLE
Compile error on PlatformIO / STM32F103C8

### ISSUE THREAD

**Issue by Stanelec** [davetcc/tcMenu#95]
When compiling the generated code in PlatformIO, it occurs the same error as described in https://github.com/davetcc/tcMenuLib/issues/72.

The error is caused by this line of code:
https://github.com/davetcc/tcMenu/blob/739f68ef9cfa774d5bd03deb007e33515f3782ca/CoreXmlPlugins/core-display/lcdSrc/tcMenuLiquidCrystal.cpp#L85

I think it should be:
```c++
 uint8_t last = min<uint8_t>(bufSz, strlen(buffer)); 
```

Thank you for your work!

**Comment by davetcc** [comment]
We’ll get the two compile errors in a patch release soon. Thanks for reporting.

**Comment by davetcc** [comment]
please could you go to the designer, where the library versions are shown, change the stream from stable to beta, and check if you still get the compile error in liquidcrystal code. We've also update tcMenuLib master with a fix too.

**Comment by davetcc** [comment]
I'm pretty sure this is fixed in plugin version 1.5.1, please try that version (beta stream at the moment) and re-open if I am wrong.

**Comment by Stanelec** [comment]
You're right, everything is compiling fine now, thank you!
